name: Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverageRun:
    name: Run Coverage
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, '[skip test]') || contains(github.event.head_commit.message, '[skip coverage run]'))"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Install NodeJS v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-14-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: |
          yarn --frozen-lockfile
      - name: Run Coverage tests
        run: "yarn run test:coverage"
      - name: Store code coverage report
        uses: actions/upload-artifact@v2-preview
        with:
          name: coverage
          path: coverage/

  coverageUploadCoveralls:
    name: Upload Coverage results to Coveralls
    needs: coverageRun
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, '[skip test]') || contains(github.event.head_commit.message, '[skip coverage upload]') || contains(github.event.head_commit.message, '[skip coverage upload coveralls]'))"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Download Coverage report
        uses: actions/download-artifact@v2-preview
        with:
          name: coverage
          path: coverage/
      - name: Coveralls Upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
